server:
   port: ${port:5001}
   servlet:
      contextPath: "/urd"

logging:
   path: "logs"
   file: "${logging.path}/urd.log"
   pattern:
      console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
      file: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
   level:
      com.br.kerberus.urd.service: DEBUG
      com.br.kerberus.urd.controller: DEBUG
      org.springframework.web: DEBUG
      org.hibernate: DEBUG

spring:
   main:
      banner-mode: "off"
   application:
      name: "urd"
   h2:
      console:
         enabled: true
         path: "/h2-console"
         settings:
            trace: true
            web-allow-others: false
   datasource:
      url: "jdbc:h2:mem:urd"
      driverClassName: "org.h2.Driver"
      username: "sa"
      password:
   jpa:
      properties:
         hibernate:
            show_sql: true
            format_sql: true
            use_sql_comments: false
            use_query_cache: false
            dialect: "org.hibernate.dialect.H2Dialect"