spring:
   main:
      banner-mode: "off"
   application:
      name: "urd"

logging:
   group:
      urd: com.br.kerberus.urd, com.br.kerberus.urd.config, com.br.kerberus.urd.entity, com.br.kerberus.urd.entity.core, com.br.kerberus.urd.exception, com.br.kerberus.urd.service
   path: "logs"
   file: "${logging.path}/${spring.application.name}.log"
   pattern:
      console: "# %d{dd-MM-yyyy HH:mm:ss.SSS} |  (%-5level) | ([%thread])  | %logger{0} | %msg%n"
      file: "# %d{dd-MM-yyyy HH:mm:ss.SSS} | %-5level |  %thread  | %logger{0} | %msg%n"
   level:
      root: off
      urd: info
      web: error
      sql: error
