server:
   port: ${port:5001}
   servlet:
      contextPath: "/urd"

logging:
   path: "logs"
   file: "${logging.path}/urd.log"
   pattern:
      console: "%highlight(%-5level) | %d{dd-MM-yyyy HH:mm:ss.SSS} | %magenta([%thread])  | %logger.%M - %msg%n"
   level:
      com.br.kerberus.urd.service: DEBUG
      com.br.kerberus.urd.controller: DEBUG
      org.springframework.web: DEBUG
      org.hibernate: DEBUG

spring:     
   main:
      banner-mode: "off"
   application:
      name: "urd"
   datasource:
      platform: "postgresql"
      url: "jdbc:postgresql://localhost:5432/urd"
      driverClassName: "org.postgresql.Driver"
      username: "urd"
      password: "urd@139575"
   jpa:
      properties:
         hibernate:
            show_sql: true
            format_sql: true
            use_sql_comments: false
            use_query_cache: false
            dialect: "org.hibernate.dialect.PostgreSQLDialect"
   flyway:
      locations: "classpath:db/migration"
      url: "jdbc:postgresql://localhost:5432/urd"
      user: "urd"
      password: "urd@139575"