server:
   port: ${port:60000}
   servlet:
      contextPath: "/urd"

logging:
   path: "logs"
   file: "${logging.path}/urd.log"
   pattern:
      console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
   level:
      com.br.kerberus.urd.service: DEBUG
      org.springframework.web: INFO
      org.hibernate: ERROR

spring:
   main:
      banner-mode: "off"
   profiles:
      active: "dev"
   application:
      name: "urd"
   h2:
      console:
         enabled: true
         path: "/h2-console"
         settings:
            trace: true
            web-allow-others: false
   datasource:
      url: "jdbc:h2:mem:urd"
      driverClassName: "org.h2.Driver"
      username: "sa"
      password:
   jpa:
      hibernate:
         ddl-auto: "validate"
      properties:
         hibernate:
            show_sql: false
            format_sql: false
            use_sql_comments: false
            use_query_cache: false
            dialect: "org.hibernate.dialect.H2Dialect"