server:
   port: ${port:5001}
   servlet:
      contextPath: "/urd"

spring:
   main:
      banner-mode: "off"
   application:
      name: "urd"
   datasource:
      platform: "postgresql"
      url: "postgres://mnvivfdseaxufy:6e78c16900d50a9bff8eae226a9739c6e6613aa33912c945f727b65202119bd7@ec2-54-235-90-0.compute-1.amazonaws.com:5432/d8c684p4i0e5g0"
      driverClassName: "org.postgresql.Driver"
      username: "mnvivfdseaxufy"
      password: "6e78c16900d50a9bff8eae226a9739c6e6613aa33912c945f727b65202119bd7"
   jpa:
      properties:
         hibernate:
            show_sql: false
            format_sql: false
            use_sql_comments: false
            use_query_cache: false
            dialect: "org.hibernate.dialect.PostgreSQLDialect"
            temp:
               use_jdbc_metadata_defaults: false

      hibernate:
         ddl-auto: validate
   flyway:
      locations: "classpath:db/migration"
      url: "postgres://mnvivfdseaxufy:6e78c16900d50a9bff8eae226a9739c6e6613aa33912c945f727b65202119bd7@ec2-54-235-90-0.compute-1.amazonaws.com:5432/d8c684p4i0e5g0"
      username: "mnvivfdseaxufy"
      password: "6e78c16900d50a9bff8eae226a9739c6e6613aa33912c945f727b65202119bd7"
      enabled: true
      table: "migration"
      baseline-on-migrate: true
      group: true

logging:
   group:
      urd: com.br.kerberus.urd, com.br.kerberus.urd.service, com.br.kerberus.urd.config, com.br.kerberus.urd.controller, com.br.kerberus.urd.core, com.br.kerberus.urd.repository, com.br.kerberus.urd.exception, com.br.kerberus.urd.core.log
      sql: org.hibernate, org.hibernate.sql, org.springframework.jdbc.core, org.flywaydb.core, org.flywaydb.core, org.hibernate.type
      web: org.springframework.core.codec, org.springframework.http, org.springframework.web
   path: "logs"
   file: "${logging.path}/${spring.application.name}.log"
   pattern:
      console: "# ${spring.application.name} | %d{dd-MM-yyyy HH:mm:ss.SSS} |  %highlight(%-5level) | %magenta([%thread])  | %logger{0} | %msg%n"
      file: "# ${spring.application.name} | %d{dd-MM-yyyy HH:mm:ss.SSS} | %-5level |  %thread  | %logger{0} | %msg%n"
   level:
      root: off
      urd: info
      web: error
      sql: error